# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoR_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='username',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.TextField(max_length=100),
        ),
    ]
